# RNA-seq pipe Docker for base build!!
# 02/28/2018


FROM ubuntu:16.04

LABEL maintainer="Wustl.Zhanglab@gmail.com"

RUN mkdir /myvol
VOLUME /myvol

# install all build-essentials
RUN apt-get update \ 
	&& apt-get install -y --no-install-recommends \
		bc \
        bzip2 \
        ca-certificates \
        curl \
        g++ \
        gcc \
        gfortran \
        git \
        less \
        libbz2-dev \
        libcurl4-openssl-dev \
        libgsl-dev \
        libgsl2 \
        liblzma-dev \
        libmysqlclient-dev \
        libncurses5-dev \
        libpcre3-dev \
        libreadline-dev \
        libssl-dev \
        libx11-dev \
        make \
        python-dev \
        texlive-latex-base texlive-latex-extra \
        unzip \
        xorg-dev \
        zlib1g-dev \
        vim \
	locales \
	debconf \
    && rm -rf /var/lib/apt/lists/* 

# fix locale issue
# the locale issue is in Singularity, so those MUST be in S.def file rather than here
# RUN apt-get install debconf
# RUN dpkg-reconfigure locales


# install R 3.3.2
RUN cd /opt/ \
    && curl -fsSL https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -o /opt/Miniconda2-latest-Linux-x86_64.sh \
    && bash Miniconda2-latest-Linux-x86_64.sh -b -p /opt/miniconda \
    && rm Miniconda2-latest-Linux-x86_64.sh \
    && ln -s /opt/miniconda/bin/conda /usr/bin/ \
    && conda config --add channels defaults \
    && conda config --add channels conda-forge \
    && conda config --add channels bioconda \
    && conda install r=3.3.2 \
    && echo 'install.packages("ggplot2",repos="http://cran.us.r-project.org")' > /opt/packages.R \
    && echo 'install.packages("cowplot",repos="http://cran.us.r-project.org")' >> /opt/packages.R \
    && echo 'install.packages("jsonlite",repos="http://cran.us.r-project.org")' >> /opt/packages.R \
    && /opt/miniconda/bin/Rscript /opt/packages.R \
    && rm /opt/packages.R \
    && mkdir -p /usr/local/lib/R/site-library


# install fastq-dump.2.8.2
RUN conda update conda \
    && conda install -y -c bioconda sra-tools=2.8.2

# install docker image id finding tools
RUN conda install -y  -c conda-forge jq

# install wigToBigWig
RUN conda update conda \ 
	&& conda install -y  ucsc-wigtobigwig

# install fastqc v0.11.7 from bioconda
RUN conda install -y  -c bioconda fastqc=0.11.7

# install preseq 2.0.0
RUN curl -fsSL http://smithlabresearch.org/downloads/preseq_linux_v2.0.tar.bz2 -o /opt/preseq_linux_v2.0.tar.bz2 \
    && tar xvjf /opt/preseq_linux_v2.0.tar.bz2 -C /opt/ \
    && ln -s /opt/preseq_v2.0/preseq /usr/local/bin/preseq \
    && ln -s /opt/preseq_v2.0/bam2mr /usr/local/bin/bam2mr \
    && rm /opt/preseq_linux_v2.0.tar.bz2 \
    # make sure that libgsl.so.0 exists beause PreSeq links to that
    && ln -s /usr/lib/x86_64-linux-gnu/libgsl.so /lib/x86_64-linux-gnu/libgsl.so.0

# install samtools v1.3.1
RUN curl -fsSL https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2 -o /opt/samtools-1.3.1.tar.bz2 \
    && tar xvjf /opt/samtools-1.3.1.tar.bz2 -C /opt/ \
    && cd /opt/samtools-1.3.1 \
    && make \
    && make install \
    && rm /opt/samtools-1.3.1.tar.bz2

# install bedtools 2.25.0
RUN curl -fsSL https://github.com/arq5x/bedtools2/releases/download/v2.25.0/bedtools-2.25.0.tar.gz -o /opt/bedtools-2.25.0.tar.gz \
    && tar -zxvf /opt/bedtools-2.25.0.tar.gz -C /opt/ \
    && cd /opt/bedtools2 \
    && make \
    && rm /opt/bedtools-2.25.0.tar.gz

# install methylQA 0.2.0
RUN cd /opt/ \
    && git clone git://github.com/lidaof/methylQA.git \
    && cd /opt/methylQA/ \
    && make \
    && cd /

# install bedGraphToBigWig
RUN conda install ucsc-bedgraphtobigwig
ENV PATH /opt/sratoolkit.2.8.2-1-ubuntu64/bin:/opt/bwa-0.7.16a/:/opt/bedtools2/bin/:/opt/methylQA/:/opt/kentUtils/bin/:/opt/miniconda/bin/:$PATH


# install STAR v2.5.4b 
RUN curl -L  https://github.com/alexdobin/STAR/archive/2.5.4b.tar.gz -o /opt/star_2.5.4b.tar.gz  && \
    cd /opt && tar -xzf star_2.5.4b.tar.gz && cd STAR-2.5.4b/source/ && \
    make STAR && \
    cp ./STAR /usr/bin/


# install multiqc
RUN pip install multiqc 

# install featureCounts
RUN conda install -y  -c bioconda subread 

# install python packages for RSeQC
RUN conda install -y rseqc
RUN conda install -y htslib=1.3.1

# install bedSort
RUN conda install -y -c bioconda ucsc-bedsort

# install Rsem v1.3.0
RUN conda install -y -c bioconda rsem=1.3.0 

# cp files from server into the image:
RUN mkdir /data
RUN mkdir /scratch
WORKDIR /data

# install python3.6 and cutadapt 1.16 (py3 based)
RUN curl https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tgz -o /opt/Python-3.6.3.tgz \
    && cd /opt && tar -xvf Python-3.6.3.tgz \
    && cd Python-3.6.3 \
    && ./configure \
    && make \
    && make install \
    && rm /opt/Python-3.6.3.tgz \
    && apt-get update \
    && apt-get install -y python3-pip \
    && pip3.6 install 'cutadapt==1.16' 


ENV PATH  $PATH:/opt/sratoolkit.2.9.1-1-ubuntu64/bin:/opt/bedtools2/bin/:/opt/methylQA/:/opt/miniconda/bin/

#add pipe code
# set date to disable catch on pipe code
#ARG CACHE_DATE=`date`
#RUN curl -o /rna_seq.tar.gz  http://brc.wustl.edu/SPACE/shaopengliu/Docker_image/rna-seq/rna_seq.tar.gz \
#    && cd / && tar -xzf /rna_seq.tar.gz \
#    && rm /rna_seq.tar.gz \
#    && conda install -c conda-forge jq 


