FROM ubuntu:16.04

# install all build-essentials
RUN apt-get update \
        && apt-get install -y --no-install-recommends \
        bc \
        bzip2 \
        ca-certificates \
        curl \
        g++ \
        gcc \
        gfortran \
        git \
        less \
        libbz2-dev \
        libcurl4-openssl-dev \
        libgsl-dev \
        libgsl2 \
        liblzma-dev \
        libmysqlclient-dev \
        libncurses5-dev \
        libpcre3-dev \
        libreadline-dev \
        libssl-dev \
        libx11-dev \
        make \
        python-dev \
        texlive-latex-base texlive-latex-extra \
        unzip \
        xorg-dev \
        zlib1g-dev \
        vim \
        python-pip \
        python-setuptools \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --upgrade pip

# install R 3.3.2
RUN cd /opt/ \
    && curl -fsSL https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -o /opt/Miniconda2-latest-Linux-x86_64.sh \
    && bash Miniconda2-latest-Linux-x86_64.sh -b -p /opt/miniconda \
    && rm Miniconda2-latest-Linux-x86_64.sh \
    && ln -s /opt/miniconda/bin/conda /usr/bin/ \
    && conda config --add channels defaults \
    && conda config --add channels conda-forge \
    && conda config --add channels bioconda \
    && conda install r=3.3.2 \
    && echo 'install.packages("ggplot2",repos="http://cran.us.r-project.org")' > /opt/packages.R \
    && echo 'install.packages("cowplot",repos="http://cran.us.r-project.org")' >> /opt/packages.R \
    && echo 'install.packages("jsonlite",repos="http://cran.us.r-project.org")' >> /opt/packages.R \
    && /opt/miniconda/bin/Rscript /opt/packages.R \
    && rm /opt/packages.R \
    && mkdir -p /usr/local/lib/R/site-library

# install preseq 2.0.0
RUN curl -fsSL http://smithlabresearch.org/downloads/preseq_linux_v2.0.tar.bz2 -o /opt/preseq_linux_v2.0.tar.bz2 \
    && tar xvjf /opt/preseq_linux_v2.0.tar.bz2 -C /opt/ \
    && ln -s /opt/preseq_v2.0/preseq /usr/local/bin/preseq \
    && ln -s /opt/preseq_v2.0/bam2mr /usr/local/bin/bam2mr \
    && rm /opt/preseq_linux_v2.0.tar.bz2 \
    # make sure that libgsl.so.0 exists beause PreSeq links to that
    && ln -s /usr/lib/x86_64-linux-gnu/libgsl.so /lib/x86_64-linux-gnu/libgsl.so.0


# install python3.6 and cutadapt 1.16 (py3 based)
RUN curl https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tgz -o /opt/Python-3.6.3.tgz \
    && cd /opt && tar -xvf Python-3.6.3.tgz \
    && cd Python-3.6.3 \
    && ./configure \
    && make \
    && make install \
    && rm /opt/Python-3.6.3.tgz \
    && apt-get update \
    && apt-get install -y python3-pip \
    && pip3.6 install 'cutadapt==1.16'

# install bwa 0.7.16a
RUN curl -fsSL https://sourceforge.net/projects/bio-bwa/files/bwa-0.7.16a.tar.bz2 -o /opt/bwa-0.7.16a.tar.bz2 \
    && tar xvjf /opt/bwa-0.7.16a.tar.bz2 -C /opt/ \
        && cd /opt/bwa-0.7.16a/ \
        && make \
        && rm /opt/bwa-0.7.16a.tar.bz2

# install samtools v1.2
RUN curl -fsSL https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2 -o /opt/samtools-1.3.1.tar.bz2 \
    && tar xvjf /opt/samtools-1.3.1.tar.bz2 -C /opt/ \
    && cd /opt/samtools-1.3.1 \
    && make \
    && make install \
    && rm /opt/samtools-1.3.1.tar.bz2

# install bedtools 2.27.0 (will be downgraded by bowtie2)
RUN conda install -y -c bioconda bedtools=2.27.1

# install bedSort
RUN conda install -y -c bioconda ucsc-bedsort

# install bowtie2 2.3.4.1
RUN conda install -y -c bioconda bowtie2=2.3.4.1

# install bgzip and tabix
RUN conda install -c bioconda tabix

# install jq for image finding
RUN conda install -y -c conda-forge jq

ENV PATH $PATH:/opt/sratoolkit.2.9.1-1-ubuntu64/bin:/opt/bwa-0.7.16a/:/opt/methylQA/:/opt/kentUtils/bin/:/opt/miniconda/bin/



# add the pipe code
ARG CACHE_DATE=2018-05-07




